### ISSUE TITLE
Fix problem with walls

### ISSUE THREAD

**Issue by arosard** [leoNord462/tank_trouble_remastered#3]
The walls displayed on the map doesn't match the walls hit when displacing the tank.
Some walls exist but are invisible.
Some walls does'nt exist but are displayed.

**Comment by lbo462** [comment]
Tank hit box is made smaller so that it can get though small corridrors ... Maybe there's a better way to do this.
But I have never encountered invisible wall or stuffs like that ...

**Comment by arosard** [comment]
Problem was with the tank not being displayed at the right place for some screen sizes.
Changed setTransform() by transform() in draw() of Tank.
The previous replaced all transforms (including the one that adapts to the sceen) by the one provided.
The new one only adds a transform.
